import Header from './components/Header';
import './globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='pt-BR'>
      <body className={poppins.className}>
        <Header />
        <main className='w-full flex items-center justify-center p-8 min-h-[calc(100vh-88px)] max-w-[1280px] mx-auto'>
          {children}
        </main>
      </body>
    </html>
  );
}
